# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f100642ddc2472d24f9fe0c0ea0d1d3bde85010be23c7137008f2e8c6db0c095c51314d2deb5c8fe3dd0edf709c267b88b3a4d7e9e4c028a45c1bb12a3f20559

test:
  secret_key_base: 8873b7443d090eae95633461473048292dda31849cb557e4d3118ebd22aafebaf633ab63b424dc49166d9ee7815f9a3c750716222616bd4c58b211251d23cbc7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
